version: 2.0.{build}

pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
skip_tags: true

image: Visual Studio 2019
platform: Any CPU

artifacts:
  - path: dist/*.nupkg
    name: NuGet Package
cache:
  - '%USERPROFILE%\.nuget\packages'
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'

build_script:
  - ps: "git submodule init -q \ngit submodule update -q \ngit submodule -q foreach git fetch origin -q \ngit submodule -q foreach git pull origin master -q"
  - ps: "dotnet pack -p:Version=$env:VERSION -p:ContinuousIntegrationBuild=true"

test_script:
  - ps: "dotnet test -p:Version=$env:VERSION -p:ContinuousIntegrationBuild=true"

for:
  - branches:
      only:
        - master
    init:
      - ps: "$env:VERSION=$env:APPVEYOR_BUILD_VERSION"
    # build_script:
    #   - ps: "git submodule init -q \ngit submodule update -q \ngit submodule -q foreach git fetch origin -q \ngit submodule -q foreach git pull origin master -q"
    #   - ps: "dotnet pack    -p:Version=$env:APPVEYOR_BUILD_VERSION -p:ContinuousIntegrationBuild=true"
    deploy:
      - provider: NuGet
        api_key:
          secure: WkhZUINbgPWyVGZh3XAB7Vi9ldaCFaSi3TSfKID+QETMUTuYiC/pFubkn6DcUjio
        on:
          branch: master

  - branches:
      only:
        - /alpha|beta|preview|rc|snapshot/
    init:
      - ps: "$env:VERSION=$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_REPO_BRANCH"
    # build_script:
    #   - ps: "git submodule init -q \ngit submodule update -q \ngit submodule foreach git fetch origin -q \ngit submodule foreach git pull origin master -q"
    #   - ps: "dotnet pack    -p:VersionPrefix=$env:APPVEYOR_BUILD_VERSION -p:VersionSuffix=$env:APPVEYOR_REPO_BRANCH -p:ContinuousIntegrationBuild=true"
    deploy:
      - provider: NuGet
        api_key:
          secure: WkhZUINbgPWyVGZh3XAB7Vi9ldaCFaSi3TSfKID+QETMUTuYiC/pFubkn6DcUjio

  - branches:
      only:
        - pr
    init:
      - ps: "$env:VERSION=$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH-$env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT"
    # build_script:
    #   - ps: "git submodule init -q \ngit submodule update -q \ngit submodule foreach git fetch origin -q \ngit submodule foreach git pull origin master -q"
    #   - ps: "dotnet pack    -p:Version=$env:APPVEYOR_BUILD_VERSION -p:VersionSuffix=$env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH-$env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT -p:ContinuousIntegrationBuild=true"