version: 2.0.{build}

pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
skip_tags: true

image: Visual Studio 2019
platform: Any CPU

artifacts:
  - path: dist/*.nupkg
    name: NuGet Package
cache:
  - '%USERPROFILE%\.nuget\packages'
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'

for:
  - branches:
      only:
        - master
    build_script:
      - ps: "git submodule init -q \ngit submodule update -q \ngit submodule foreach git fetch origin -q \ngit submodule foreach git pull origin master -q"
      - ps: "dotnet restore -p:VersionPrefix=$env:APPVEYOR_BUILD_VERSION -p:VersionSuffix="
      - ps: "dotnet build   -p:VersionPrefix=$env:APPVEYOR_BUILD_VERSION -p:VersionSuffix= --no-restore"
      - ps: "dotnet pack    -p:VersionPrefix=$env:APPVEYOR_BUILD_VERSION -p:VersionSuffix= --no-restore --no-build"
    deploy:
      - provider: NuGet
        api_key:
          secure: WkhZUINbgPWyVGZh3XAB7Vi9ldaCFaSi3TSfKID+QETMUTuYiC/pFubkn6DcUjio
        on:
          branch: master

  - branches:
      only:
        - preview
        - rc
    build_script:
      - ps: "git submodule init -q \ngit submodule update -q \ngit submodule foreach git fetch origin -q \ngit submodule foreach git pull origin master -q"
      - ps: "dotnet restore -p:VersionPrefix=$env:APPVEYOR_BUILD_VERSION -p:VersionSuffix=$env:APPVEYOR_REPO_BRANCH"
      - ps: "dotnet build   -p:VersionPrefix=$env:APPVEYOR_BUILD_VERSION -p:VersionSuffix=$env:APPVEYOR_REPO_BRANCH --no-restore"
      - ps: "dotnet pack    -p:VersionPrefix=$env:APPVEYOR_BUILD_VERSION -p:VersionSuffix=$env:APPVEYOR_REPO_BRANCH --no-restore --no-build"
    deploy:
      - provider: NuGet
        api_key:
          secure: WkhZUINbgPWyVGZh3XAB7Vi9ldaCFaSi3TSfKID+QETMUTuYiC/pFubkn6DcUjio

  - branches:
      only:
        - pr
    build_script:
      - ps: "git submodule init -q \ngit submodule update -q \ngit submodule foreach git fetch origin -q \ngit submodule foreach git pull origin master -q"
      - ps: "dotnet restore -p:VersionPrefix=$env:APPVEYOR_BUILD_VERSION -p:VersionSuffix=$env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH-$env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT"
      - ps: "dotnet build   -p:VersionPrefix=$env:APPVEYOR_BUILD_VERSION -p:VersionSuffix=$env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH-$env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT --no-restore"
      - ps: "dotnet pack    -p:VersionPrefix=$env:APPVEYOR_BUILD_VERSION -p:VersionSuffix=$env:APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH-$env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT --no-restore --no-build"