version: 1.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2019
platform: Any CPU
environment:
cache:
- '%USERPROFILE%\.nuget\packages' -> packet.lock
- '%LocalAppData%\NuGet\Cache' -> packet.lock
- '%LocalAppData%\NuGet\v3-cache' -> paket.lock
- paket-files -> packet.lock
build_script:
- ps: "git submodule init -q \ngit submodule update -q \ngit submodule foreach git fetch origin -q \ngit submodule foreach git pull origin master -q \ncd codebase\ndotnet tool install fake-cli --tool-path .\\.tools\n.\\.tools\\fake --silent run .\\build.fsx"
artifacts:
- path: dist/*.nupkg
  name: NuGet Package
deploy:
- provider: NuGet
  api_key:
    secure: Q6ho6fe6sOA1/bPGHAguZAvVxNK9xugl/CteNAa9Pqzj61RzTPwLS8Ivabg+CS15
  on:
    branch: master