version: 2.0.{build}

pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
skip_tags: true
image: Visual Studio 2019
platform: Any CPU
build_script:
  - ps: "git submodule init -q \ngit submodule update -q \ngit submodule foreach git fetch origin -q \ngit submodule foreach git pull origin master -q \ncd dist \nmkdir restore \ncd .. \ncd codebase\ndotnet tool install fake-cli --tool-path .\\.tools\n.\\.tools\\fake --silent run .\\build.fsx"
artifacts:
  - path: dist/*.nupkg
    name: NuGet Package
cache:
  - '%USERPROFILE%\.nuget\packages'
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'

for:
  - branches:
      only:
        - master
    deploy:
      - provider: NuGet
        api_key:
          secure: WkhZUINbgPWyVGZh3XAB7Vi9ldaCFaSi3TSfKID+QETMUTuYiC/pFubkn6DcUjio

  - branches:
      only:
        - preview
    deploy:
      - provider: NuGet
        api_key:
          secure: WkhZUINbgPWyVGZh3XAB7Vi9ldaCFaSi3TSfKID+QETMUTuYiC/pFubkn6DcUjio

  - branches:
      only:
        - rc
    deploy:
      - provider: NuGet
        api_key:
          secure: WkhZUINbgPWyVGZh3XAB7Vi9ldaCFaSi3TSfKID+QETMUTuYiC/pFubkn6DcUjio