// <auto-generated>
//     Generated by the FSharp WriteCodeFragment class.
// </auto-generated>
namespace FSharp

open System
open System.Reflection


[<assembly: AssemblyTitle("Axle.FSharp")>]
[<assembly: AssemblyProduct("Axle.FSharp")>]
[<assembly: AssemblyDescription("Axle Framework F#-friendly Library")>]
[<assembly: AssemblyCompany("Virtual Dimensions")>]
[<assembly: AssemblyCopyright("Copyright © Virtual Dimensions 2013-2018")>]
[<assembly: AssemblyTrademark("")>]
[<assembly: AssemblyConfiguration("Debug")>]
[<assembly: AssemblyCulture("")>]
[<assembly: System.Runtime.InteropServices.GuidAttribute("{058DA5D4-BE62-4A66-AC23-DD162E113EBF}")>]
[<assembly: AssemblyVersion("1.5.2168.31463")>]
[<assembly: AssemblyFileVersion("1.5.2168.31463")>]
[<assembly: AssemblyInformationalVersion("1.5.2168.31463")>]
do()
