// <auto-generated>
//     Generated by the FSharp WriteCodeFragment class.
// </auto-generated>
namespace FSharp

open System
open System.Reflection


[<assembly: AssemblyTitle("Axle.Forest")>]
[<assembly: AssemblyProduct("Axle.Forest")>]
[<assembly: AssemblyDescription("Axle integration with the Forest framework")>]
[<assembly: AssemblyCompany("Virtual Dimensions")>]
[<assembly: AssemblyCopyright("Copyright © Virtual Dimensions 2013-2018")>]
[<assembly: AssemblyTrademark("")>]
[<assembly: AssemblyConfiguration("Debug")>]
[<assembly: AssemblyCulture("")>]
[<assembly: System.Runtime.InteropServices.GuidAttribute("{5A6B7C35-2A40-4860-9B21-9AA13284F809}")>]
[<assembly: AssemblyVersion("1.5.2168.30260")>]
[<assembly: AssemblyFileVersion("1.5.2168.30260")>]
[<assembly: AssemblyInformationalVersion("1.5.2168.30260")>]
do()
