// <auto-generated>
//     Generated by the FSharp WriteCodeFragment class.
// </auto-generated>
namespace FSharp

open System
open System.Reflection


[<assembly: AssemblyTitle("Axle.Data.FSharp")>]
[<assembly: AssemblyProduct("Axle.Data.FSharp")>]
[<assembly: AssemblyDescription("Axle Data F#-friendly Library")>]
[<assembly: AssemblyCompany("Virtual Dimensions")>]
[<assembly: AssemblyCopyright("Copyright © Virtual Dimensions 2013-2019")>]
[<assembly: AssemblyTrademark("")>]
[<assembly: AssemblyConfiguration("Debug")>]
[<assembly: AssemblyCulture("")>]
[<assembly: System.Runtime.InteropServices.GuidAttribute("{5E088541-AAA7-427B-9C45-757C73875B2C}")>]
[<assembly: AssemblyVersion("1.6.2463.24892")>]
[<assembly: AssemblyFileVersion("1.6.2463.24892")>]
[<assembly: AssemblyInformationalVersion("1.6.2463.24892")>]
do()
